### PR TITLE
Files follows title name, fix links, and add contact

### PR DESCRIPTION
**Pull request by kairoaraujo**
- Rename files to be aligned with the title
  - installation -> deployment
  - overview -> introduction

- Add contact info
- Fixed some links

Signed-off-by: Kairo de Araujo <kdearaujo@vmware.com>

### CODE REVIEW

**Review by MVrachev — COMMENTED** [review]
If you want to change `installation` to `deployment` you can also rename the `docs/source/guide/deployment/custom_installation.rst` file to `custom_deployment.rst`
and in the `custom_installation.rst` file itself you have used `installation`. 

Also, you have used `installation` in the `all_in_one.rst` file, you can replace it with `deployment` there as well.

**Review by MVrachev — COMMENTED** [review]
I noticed a couple of other places where `installation` has to be replaced:
- line 102 in `docs/source/guide/deployment/all_in_one.rst`.
- line 7 in `docs/source/guide/repository-service-tuf-cli/index.rst`

Also `overview` in line `66` in `README.md`.

**Comment by kairoaraujo** [comment]
> I noticed a couple of other places where `installation` has to be replaced:
> 
> * line 102 in `docs/source/guide/deployment/all_in_one.rst`.
> * line 7 in `docs/source/guide/repository-service-tuf-cli/index.rst`
> 
> Also `overview` in line `66` in `README.md`.

line 7 in `docs/source/guide/repository-service-tuf-cli/index.rst` is not part of this documentation. It is repository-service-tuf-cli.

**Review by MVrachev — APPROVED** [review]
> line 7 in `docs/source/guide/repository-service-tuf-cli/index.rst` is not part of this documentation. It is repository-service-tuf-cli.

Yes, my mistake.

I agree with the changes.
Merging.

**Pull request merged**
